// Resume Content

export default {
  tagLine: "Web Developer | JavaScript Specialist | Quality Mindset",
  education: [
    {
      type: "degree",
      title: "BA, International Relations",
      institution: "University of California, Davis",
      location: "Davis, CA",
      date: 2005,
    },
    {
      type: "degree",
      title: "M.Ed, Curriculum and Instruction",
      institution: "Portland State University",
      location: "Portland, OR",
      date: 2009,
    },
    {
      type: "certificate",
      title: "Full Stack Development Course",
      duration: "700 hrs",
      institution: "Epicodus",
      location: "Portland, OR",
      date: 2014,
    },
    {
      type: "certificate",
      title: "React/Redux Intensive Workshop",
      duration: "40 hrs",
      institution: "Alchemy Code Lab",
      location: "Portland, OR",
      date: 2017,
    },
    {
      type: "certificate",
      title: "GraphQL Intensive Workshop",
      duration: "16 hrs",
      institution: "Cascadia JS 2019",
      location: "Seattle, WA",
      date: 2019,
    },
  ],
  essentialSkills: [
    "Efficient researcher and autodidact",
    "Constant and humble learner",
    "Skilled communicator across mediums and audience types",
    "Strong interpersonal skills",
    "Empathetic and dedicated mentor",
  ],
  technicalSkills: [
    {
      label: "Languages and Frameworks",
      content: [
        "Modern JavaScript",
        "TypeScript",
        "React/Redux",
        "Vue/Vuex",
        "Node.js",
        "GraphQL",
        "Express.js",
        "Postgres",
      ],
    },
    {
      label: "Testing",
      content: [
        "Jest",
        "Cypress",
        "Puppeteer",
        "Ava",
        "Mocha",
        "Sinon",
        "Postman",
        "TestRail",
      ],
    },
    {
      label: "Tooling and DevOps",
      content: [
        "Git/Gitflow",
        "Storybook",
        "Docker",
        "Jenkins",
        "TeamCity",
        "AWS",
      ],
    },
    {
      label: "Workflow",
      content: [
        "Scrum/KanBan",
        "Pair Programming",
        "Jira",
        "Confluence",
        "GitHub",
        "Trello",
      ],
    },
  ],
  webdevExperience: [
    {
      company: "Agile MD",
      location: "Remote",
      title: "Senior Software Engineer",
      startDate: "October 2022",
      endDate: "July 2023",
      highlights: [
        "Leveraged multiple information sources including source code, documentation, and coworker interviews to quickly form a mental model of business logic and systems",
        "Made increasingly complex contributions fixing defects, refactoring outdated code and implementing polished user interface features across multiple complex frontend products (TypeScript, React, Redux)",
        "Developed relationships and worked closely with cross-functional team members to gather broad context on feature requirements and drive efficient implementation",
        "Sought out and delivered on opportunities for non-technical contributions including writing detailed documentation, preparing and delivering demonstrations, and engaging in product strategy discussions",
        "Contributed to two onsite hackathon projects developing valuable tooling innovations (feature flagging, Open API specification)",
      ],
    },
    {
      company: "New Relic",
      location: "Remote",
      title: "Senior Software Engineer",
      startDate: "October 2021",
      endDate: "October 2022",
      highlights: [
        "Led frontend development efforts on a team developing rich UI features (TypeScript, React) to help New Relic users understand their data consumption, retention and limits",
        "Communicated frequently with product owner, engineering manager, designer and other key organizational stakeholders to draft early stage features, create high level design documents and engineering-ready tickets",
        "Coordinated engineering task distribution among team members, conducted frequent checkins to assess progress or blockers, and provided detailed code reviews and mentoring to drive features to release",
        "Participated in a regular on-call pager rotation to triage and mitigate production system incidents",
        "Identified critical technical debt and other opportunities for refactoring. Integrated this work into the development budget/cadence to ensure codebase stayed current",
        "Budgeted time for innovation and industry best practices review to explore leading opportunities for improvement to development process and experience",
      ],
    },
    {
      company: "New Relic",
      location: "Remote",
      title: "Software Engineer",
      startDate: "October 2020",
      endDate: "October 2021",
      highlights: [
        "Led development of several large features by delivering incremental value during development via vertical slices of work, communicating regularly with key stakeholders to keep expectations aligned, and distributing work efficiently",
        "Onboarded quickly to a different team for a two month assignment to help them deliver a critical UI feature for an on-time launch",
        "Championed tooling and process improvements, including improving automated test coverage and incorporating organized bug bashes into large feature development guidelines",
        "Provided mentorship to junior engineers via code reviews and pair programming",
        "Wrote internal technical documentation around features, team processes and tech debt reduction to inform stakeholders and broaden impact of work beyond team",
      ],
    },
    {
      company: "Insitu",
      location: "Remote",
      title: "Software Developer III",
      startDate: "June 2018",
      endDate: "October 2020",
      highlights: [
        "Implemented UI features and bug fixes for a media analysis application (Vue, Vuex)",
        "Led development of multiple robustly tested microservices (Node, Express, Jest), implementing best practices in areas including validation, caching, authentication, and REST API design",
        "Championed continuous reflection and improvement of QA process across two teams, from implementing first-class automated tests to introducing black-box / exploratory testing into development cycle",
        "Led overhaul of an application's local development setup (Docker, Docker-Compose, Nginx) to create an easily reproducible and more production-like system",
        "Led implementation of a comprehensive suite of UI automation tests (Cypress) across two different applications (500+ tests), resulting in dramatic improvements in test reliability, performance, and maintainability",
      ],
    },
    {
      company: "Incomm",
      location: "Portland, OR",
      title: "Software Engineer in Test",
      startDate: "May 2016",
      endDate: "May 2018",
      highlights: [
        "Worked directly with front end engineers to implement a modern user interface for an internal admin application (React, Redux, Jest)",
        "Transitioned to leadership role in the extension, maintenance and integration of automated UI and API testing frameworks. Reduced weekly regression testing time from days to hours",
        "Contributed to a continuous delivery pipeline infrastructure-as-code prototype, providing for safe, automated deployments of a microservice to production on the merging of a pull request",
        "Developed feature branch validation system via VCS host (GitHub) and CI tool (TeamCity)",
        "Provided training, code reviews and mentorship to new QA engineers",
      ],
    },
    {
      company: "Incomm",
      location: "Portland, OR",
      title: "Associate QA Engineer",
      startDate: "December 2014",
      endDate: "May 2016",
      highlights: [
        "Collaborated with senior SET to build an end-to-end automated UI testing repository (Protractor) for customer and internal-facing applications",
        "Designed API testing framework using npm libraries (Ava, Request-Promise, Yeoman) and custom JavaScript to dramatically improve API layer test coverage",
        "Daily experience with an agile sprint development cycle and associated processes/tools",
        "Conducted increasingly complex exploratory test sessions for bug and feature stories as a QA member of an 8-person cross functional product team",
        "Active contributor to regular agile ceremonies and other specialized working groups",
      ],
    },
  ],
  communityContributions: [
    {
      type: "event",
      year: "2018 / 2019",
      title: "Hack the Dot",
      role: "Lead Organizer",
      location: "Portland, OR",
      description:
        "Planned and coordinated three beginner friendly one-night hackathons around building a website for a mystery domain name",
    },
    {
      type: "talk",
      year: "2018",
      title: "Front End PDX",
      role: "Speaker",
      location: "Portland, OR",
      description:
        "Prepared and gave a detailed presentation on using tooling to create deterministic dependency trees for JavaScript projects",
    },
    {
      type: "workshop",
      year: "2018",
      title: "ACT-W Portland",
      role: "Instructor",
      location: "Portland, OR",
      description:
        "Prepared and gave a detailed tutorial on testing web applications with Cypress",
    },
  ],
  personalInterests: [
    "Long Distance Backpacking",
    "Highly Amateur Carpentry",
    "High Risk Juggling",
  ],
  contactInformation: [
    "+1 503 867 2387",
    "ckdanielsen@gmail.com",
    "hotmess.codes",
  ],
}
